# Site
url: "https://www.kuzine.net.tr"
lang: tr
title: Kuzine
description: Yemek k端lt端r端ne keyifli bir yolculuk.
logo: "/images/logo.png"
copyright: '<a href="https://www.melihkocaturk.com" class="text-black-50 text-decoration-none">Melih Kocat端rk</a>'

# Permalinks
permalink: /:title

# Pagination
paginate: 10
paginate_path: /sayfa:num/

# Google Analytics
google_analytics: G-J3008RYHE2

# Plugins
plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-feed
